#!/usr/bin/env bash
# Provision + deploy the interview-insights backend to Azure.
#
# Idempotent: re-running the script after a successful run only
# re-applies app settings + rebuilds/redeploys the container. Resources
# that already exist are left alone.
#
# Requires:
#   - az CLI logged in (`az login`)
#   - The active subscription is the one you want to deploy into
#     (override with: `az account set --subscription <id>`)
#
# Usage:
#   ./backend/scripts/deploy_azure.sh

set -euo pipefail

# ---------------------------------------------------------------------------
# Config — override via env vars if you want different names / region.
# ---------------------------------------------------------------------------

LOCATION="${LOCATION:-centralindia}"
RG="${RG:-rg-interview-insights}"

# Stable suffix so globally-unique resource names stay predictable across
# re-runs. Override AZ_SUFFIX in your shell if you want a fresh stack.
SUBSCRIPTION_ID="$(az account show --query id -o tsv)"
DEFAULT_SUFFIX="$(printf '%s' "${SUBSCRIPTION_ID}" | shasum | cut -c1-6)"
AZ_SUFFIX="${AZ_SUFFIX:-${DEFAULT_SUFFIX}}"

ACR="${ACR:-criiapp${AZ_SUFFIX}}"
ASP="${ASP:-asp-interview-insights}"
APP="${APP:-app-iiapi-${AZ_SUFFIX}}"

PG_SERVER="${PG_SERVER:-pg-iiapp-${AZ_SUFFIX}}"
PG_DB="${PG_DB:-interview_insights}"
PG_ADMIN="${PG_ADMIN:-iiadmin}"

STORAGE_ACCOUNT="${STORAGE_ACCOUNT:-stiiapp${AZ_SUFFIX}}"
CONTAINER_AUDIO="${CONTAINER_AUDIO:-audio}"
CONTAINER_TRANSCRIPTS="${CONTAINER_TRANSCRIPTS:-transcripts}"

KEY_VAULT="${KEY_VAULT:-kv-iiapp-${AZ_SUFFIX}}"

IMAGE_REPO="backend"
IMAGE_TAG="${IMAGE_TAG:-latest}"

# Backend code lives one level up from this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ---------------------------------------------------------------------------
# Required secrets — read from .env or environment. Anthropic + AssemblyAI
# keys aren't generated by Azure; you provide them.
# ---------------------------------------------------------------------------

if [[ -z "${ANTHROPIC_API_KEY:-}" ]] || [[ -z "${ASSEMBLYAI_API_KEY:-}" ]]; then
    REPO_ENV="$(cd "${BACKEND_DIR}/.." && pwd)/.env"
    if [[ -f "${REPO_ENV}" ]]; then
        # Pull just the two keys we need (don't `source` the whole file,
        # to avoid clobbering other vars).
        # shellcheck disable=SC2046
        export $(grep -E '^(ANTHROPIC_API_KEY|ASSEMBLYAI_API_KEY)=' "${REPO_ENV}" | xargs)
    fi
fi

: "${ANTHROPIC_API_KEY:?Set ANTHROPIC_API_KEY (env or .env)}"
: "${ASSEMBLYAI_API_KEY:?Set ASSEMBLYAI_API_KEY (env or .env)}"

log() { printf '\n\033[1;34m▸\033[0m %s\n' "$*"; }

az_show() {
    # Run `az ... show` quietly; return 0 if found, 1 if not.
    "$@" --only-show-errors >/dev/null 2>&1
}

# ---------------------------------------------------------------------------
# 1. Resource group
# ---------------------------------------------------------------------------

log "Resource group: ${RG} (${LOCATION})"
az group create --name "${RG}" --location "${LOCATION}" --only-show-errors >/dev/null

# ---------------------------------------------------------------------------
# 2. Azure Container Registry
# ---------------------------------------------------------------------------

log "ACR: ${ACR}"
if ! az_show az acr show --name "${ACR}" --resource-group "${RG}"; then
    az acr create \
        --resource-group "${RG}" \
        --name "${ACR}" \
        --sku Basic \
        --location "${LOCATION}" \
        --only-show-errors >/dev/null
fi
ACR_LOGIN_SERVER="$(az acr show --name "${ACR}" --resource-group "${RG}" --query loginServer -o tsv)"

# ---------------------------------------------------------------------------
# 3. Storage account + Blob containers
# ---------------------------------------------------------------------------

log "Storage account: ${STORAGE_ACCOUNT}"
if ! az_show az storage account show --name "${STORAGE_ACCOUNT}" --resource-group "${RG}"; then
    az storage account create \
        --name "${STORAGE_ACCOUNT}" \
        --resource-group "${RG}" \
        --location "${LOCATION}" \
        --sku Standard_LRS \
        --kind StorageV2 \
        --allow-blob-public-access false \
        --only-show-errors >/dev/null
fi

for CONTAINER in "${CONTAINER_AUDIO}" "${CONTAINER_TRANSCRIPTS}"; do
    az storage container create \
        --account-name "${STORAGE_ACCOUNT}" \
        --name "${CONTAINER}" \
        --auth-mode login \
        --public-access off \
        --only-show-errors >/dev/null
done

# ---------------------------------------------------------------------------
# 4. Key Vault
# ---------------------------------------------------------------------------

log "Key Vault: ${KEY_VAULT}"
if ! az_show az keyvault show --name "${KEY_VAULT}" --resource-group "${RG}"; then
    az keyvault create \
        --name "${KEY_VAULT}" \
        --resource-group "${RG}" \
        --location "${LOCATION}" \
        --sku standard \
        --enable-rbac-authorization true \
        --only-show-errors >/dev/null
fi

# Grant the current user the Key Vault Secrets Officer role so we can
# write secrets (RBAC auth is on; data-plane permissions don't fall back
# to the access policy).
CURRENT_USER_OID="$(az ad signed-in-user show --query id -o tsv)"
KV_SCOPE="$(az keyvault show --name "${KEY_VAULT}" --query id -o tsv)"
az role assignment create \
    --assignee-object-id "${CURRENT_USER_OID}" \
    --assignee-principal-type User \
    --role "Key Vault Secrets Officer" \
    --scope "${KV_SCOPE}" \
    --only-show-errors >/dev/null 2>&1 || true

# Wait briefly for the role to propagate before writing secrets.
sleep 15

# ---------------------------------------------------------------------------
# 5. Postgres Flexible Server
# ---------------------------------------------------------------------------

log "Postgres Flexible: ${PG_SERVER}"
if ! az_show az postgres flexible-server show --name "${PG_SERVER}" --resource-group "${RG}"; then
    # Generate an admin password once; persist in Key Vault so re-runs
    # reuse the same value rather than regenerating.
    PG_PWD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)Aa1!"
    az postgres flexible-server create \
        --resource-group "${RG}" \
        --name "${PG_SERVER}" \
        --location "${LOCATION}" \
        --tier Burstable \
        --sku-name Standard_B1ms \
        --storage-size 32 \
        --version 16 \
        --admin-user "${PG_ADMIN}" \
        --admin-password "${PG_PWD}" \
        --public-access 0.0.0.0 \
        --yes \
        --only-show-errors >/dev/null

    az keyvault secret set \
        --vault-name "${KEY_VAULT}" \
        --name "POSTGRES-ADMIN-PASSWORD" \
        --value "${PG_PWD}" \
        --only-show-errors >/dev/null
else
    PG_PWD="$(az keyvault secret show \
        --vault-name "${KEY_VAULT}" \
        --name POSTGRES-ADMIN-PASSWORD \
        --query value -o tsv)"
fi

# Create the application database (idempotent — silently no-ops if it exists).
az postgres flexible-server db create \
    -g "${RG}" \
    -s "${PG_SERVER}" \
    -n "${PG_DB}" \
    --only-show-errors >/dev/null 2>&1 || true

# Open firewall for the operator's current IP so alembic from this
# machine can connect. (Azure services rule was set by --public-access 0.0.0.0.)
MY_IP="$(curl -fsS https://api.ipify.org)"
az postgres flexible-server firewall-rule create \
    -g "${RG}" \
    -s "${PG_SERVER}" \
    -n "operator-laptop" \
    --start-ip-address "${MY_IP}" \
    --end-ip-address "${MY_IP}" \
    --only-show-errors >/dev/null 2>&1 || true

PG_HOST="$(az postgres flexible-server show \
    --resource-group "${RG}" \
    --name "${PG_SERVER}" \
    --query fullyQualifiedDomainName -o tsv)"

DATABASE_URL="postgresql+asyncpg://${PG_ADMIN}:${PG_PWD}@${PG_HOST}:5432/${PG_DB}?ssl=require"

# ---------------------------------------------------------------------------
# 6. Write app secrets to Key Vault
# ---------------------------------------------------------------------------

log "Writing secrets to Key Vault"
az keyvault secret set --vault-name "${KEY_VAULT}" --name DATABASE-URL --value "${DATABASE_URL}" --only-show-errors >/dev/null
az keyvault secret set --vault-name "${KEY_VAULT}" --name ANTHROPIC-API-KEY --value "${ANTHROPIC_API_KEY}" --only-show-errors >/dev/null
az keyvault secret set --vault-name "${KEY_VAULT}" --name ASSEMBLYAI-API-KEY --value "${ASSEMBLYAI_API_KEY}" --only-show-errors >/dev/null

DATABASE_URL_SECRET_ID="$(az keyvault secret show --vault-name "${KEY_VAULT}" --name DATABASE-URL --query id -o tsv)"
ANTHROPIC_SECRET_ID="$(az keyvault secret show --vault-name "${KEY_VAULT}" --name ANTHROPIC-API-KEY --query id -o tsv)"
ASSEMBLYAI_SECRET_ID="$(az keyvault secret show --vault-name "${KEY_VAULT}" --name ASSEMBLYAI-API-KEY --query id -o tsv)"

# ---------------------------------------------------------------------------
# 7. Build + push container image via ACR Build (server-side; no local Docker)
# ---------------------------------------------------------------------------

log "Building image via ACR (server-side build)"
az acr build \
    --registry "${ACR}" \
    --image "${IMAGE_REPO}:${IMAGE_TAG}" \
    --file "${BACKEND_DIR}/Dockerfile" \
    "${BACKEND_DIR}" \
    --only-show-errors >/dev/null

# ---------------------------------------------------------------------------
# 8. App Service Plan
# ---------------------------------------------------------------------------

log "App Service plan: ${ASP}"
if ! az_show az appservice plan show --name "${ASP}" --resource-group "${RG}"; then
    az appservice plan create \
        --name "${ASP}" \
        --resource-group "${RG}" \
        --is-linux \
        --sku B1 \
        --location "${LOCATION}" \
        --only-show-errors >/dev/null
fi

# ---------------------------------------------------------------------------
# 9. Web App (Linux container)
# ---------------------------------------------------------------------------

log "Web App: ${APP}"
if ! az_show az webapp show --name "${APP}" --resource-group "${RG}"; then
    az webapp create \
        --name "${APP}" \
        --resource-group "${RG}" \
        --plan "${ASP}" \
        --deployment-container-image-name "${ACR_LOGIN_SERVER}/${IMAGE_REPO}:${IMAGE_TAG}" \
        --only-show-errors >/dev/null
fi

# Enable system-assigned managed identity.
az webapp identity assign \
    --name "${APP}" \
    --resource-group "${RG}" \
    --only-show-errors >/dev/null
APP_MI_OID="$(az webapp identity show --name "${APP}" --resource-group "${RG}" --query principalId -o tsv)"

# Grant the Web App's MI the roles it needs.
log "Granting RBAC to the Web App's managed identity"
ACR_SCOPE="$(az acr show --name "${ACR}" --query id -o tsv)"
STORAGE_SCOPE="$(az storage account show --name "${STORAGE_ACCOUNT}" --resource-group "${RG}" --query id -o tsv)"

for ROLE_AND_SCOPE in \
    "AcrPull|${ACR_SCOPE}" \
    "Storage Blob Data Contributor|${STORAGE_SCOPE}" \
    "Key Vault Secrets User|${KV_SCOPE}" ; do
    ROLE="${ROLE_AND_SCOPE%%|*}"
    SCOPE="${ROLE_AND_SCOPE##*|}"
    az role assignment create \
        --assignee-object-id "${APP_MI_OID}" \
        --assignee-principal-type ServicePrincipal \
        --role "${ROLE}" \
        --scope "${SCOPE}" \
        --only-show-errors >/dev/null 2>&1 || true
done

# Switch the Web App to pull from ACR using its managed identity.
az webapp config container set \
    --name "${APP}" \
    --resource-group "${RG}" \
    --container-image-name "${ACR_LOGIN_SERVER}/${IMAGE_REPO}:${IMAGE_TAG}" \
    --container-registry-url "https://${ACR_LOGIN_SERVER}" \
    --only-show-errors >/dev/null

az resource update \
    --resource-group "${RG}" \
    --name "${APP}" \
    --resource-type "Microsoft.Web/sites" \
    --set properties.siteConfig.acrUseManagedIdentityCreds=true \
    --only-show-errors >/dev/null

# ---------------------------------------------------------------------------
# 10. App settings (Key Vault references + plain config)
# ---------------------------------------------------------------------------

log "Setting Web App configuration"
az webapp config appsettings set \
    --name "${APP}" \
    --resource-group "${RG}" \
    --settings \
        "DATABASE_URL=@Microsoft.KeyVault(SecretUri=${DATABASE_URL_SECRET_ID})" \
        "ANTHROPIC_API_KEY=@Microsoft.KeyVault(SecretUri=${ANTHROPIC_SECRET_ID})" \
        "ASSEMBLYAI_API_KEY=@Microsoft.KeyVault(SecretUri=${ASSEMBLYAI_SECRET_ID})" \
        "STORAGE_BACKEND=azure_blob" \
        "AZURE_STORAGE_ACCOUNT=${STORAGE_ACCOUNT}" \
        "AZURE_STORAGE_CONTAINER_AUDIO=${CONTAINER_AUDIO}" \
        "AZURE_STORAGE_CONTAINER_TRANSCRIPTS=${CONTAINER_TRANSCRIPTS}" \
        "CORS_ALLOW_ORIGINS=*" \
        "WEBSITES_PORT=8000" \
        "WEBSITES_ENABLE_APP_SERVICE_STORAGE=false" \
    --only-show-errors >/dev/null

# Force a fresh container pull/restart so new image + settings take effect.
az webapp restart --name "${APP}" --resource-group "${RG}" --only-show-errors >/dev/null

# ---------------------------------------------------------------------------
# 11. Done — print URLs + next-step migration command.
# ---------------------------------------------------------------------------

APP_URL="https://$(az webapp show --name "${APP}" --resource-group "${RG}" --query defaultHostName -o tsv)"

cat <<EOF

============================================================
Deployment complete.

Backend URL:    ${APP_URL}
Health check:   ${APP_URL}/api/v1/health

Postgres host:  ${PG_HOST}
Database:       ${PG_DB}

Next steps:
  1. Run migrations from this machine (firewall already allows your IP):

     DATABASE_URL='${DATABASE_URL}' uv run alembic upgrade head

  2. Set Vercel env var NEXT_PUBLIC_API_URL=${APP_URL}/api/v1 then redeploy.

  3. Stream backend logs:

     az webapp log tail --name ${APP} --resource-group ${RG}

============================================================
EOF
