/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return ``{status, db}``. 200 if DB reachable, 503 otherwise.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interviews */
        get: operations["list_interviews_api_v1_projects__project_id__interviews_get"];
        put?: never;
        /**
         * Create Interview
         * @description Create an interview row, persist the upload, kick off the pipeline.
         *
         *     v1.1: accepts EITHER ``audio`` or ``transcript`` (exactly one).
         *     Zero or both is a 422 with ``errors[0].loc == ["audio"]`` so the
         *     frontend can render the message under the upload picker.
         */
        post: operations["create_interview_api_v1_projects__project_id__interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/{interview_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview */
        get: operations["get_interview_api_v1_interviews__interview_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/{interview_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Interview */
        post: operations["retry_interview_api_v1_interviews__interview_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/{interview_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Audio */
        get: operations["stream_audio_api_v1_interviews__interview_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Insights */
        get: operations["get_project_insights_api_v1_projects__project_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/insights/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Project Insights */
        post: operations["refresh_project_insights_api_v1_projects__project_id__insights_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_interview_api_v1_projects__project_id__interviews_post */
        Body_create_interview_api_v1_projects__project_id__interviews_post: {
            type: components["schemas"]["InterviewType"];
            /** Demographics */
            demographics: string;
            /** Audio */
            audio?: string | null;
            /** Transcript */
            transcript?: string | null;
            /** Meeting Notes */
            meeting_notes?: string | null;
        };
        /**
         * DemographicsSchema
         * @description Demographics block attached to every Interview row.
         *
         *     Every field is required; the frontend renders dropdowns for each
         *     enum. ``country`` is stored as ISO 3166-1 alpha-2 (e.g. ``US``,
         *     ``IN``); we accept either case and normalize to uppercase before
         *     validation so the downstream consumers always see a canonical code.
         */
        DemographicsSchema: {
            /** Name */
            name: string;
            gender: components["schemas"]["Gender"];
            /** Age */
            age: number;
            income: components["schemas"]["Income"];
            marital_status: components["schemas"]["MaritalStatus"];
            /** Country */
            country: string;
            job_role: components["schemas"]["JobRole"];
            industry: components["schemas"]["Industry"];
        };
        /**
         * Gender
         * @description Interviewee gender. See SPEC.md.
         * @enum {string}
         */
        Gender: "male" | "female" | "non_binary" | "prefer_not_to_say";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Income
         * @description Household income bracket (USD).
         * @enum {string}
         */
        Income: "under_25k" | "25k_50k" | "50k_100k" | "100k_200k" | "over_200k" | "prefer_not_to_say";
        /**
         * Industry
         * @description Interviewee industry bucket.
         * @enum {string}
         */
        Industry: "saas_software" | "ecommerce_retail" | "finance_fintech" | "healthcare" | "education" | "media_entertainment" | "manufacturing" | "government_nonprofit" | "hospitality_travel" | "other";
        /**
         * InsightStatus
         * @description Lifecycle of a per-project Claude-generated summary.
         *
         *     The synthesised "no row yet" state served by GET is ``idle`` with
         *     a null ``summary_markdown``; ``generating`` is the in-flight state
         *     after ``POST /refresh``; ``failed`` is set when the BackgroundTask
         *     catches an exception from Claude.
         * @enum {string}
         */
        InsightStatus: "idle" | "generating" | "failed";
        /**
         * InterviewListResponse
         * @description List wrapper used by ``GET /api/v1/projects/{project_id}/interviews``.
         */
        InterviewListResponse: {
            /** Items */
            items: components["schemas"]["InterviewRead"][];
        };
        /**
         * InterviewRead
         * @description Response shape for interview endpoints.
         *
         *     ``pain_points`` is embedded; ordering is the service layer's job
         *     (``severity DESC, created_at ASC``).
         */
        InterviewRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            source_kind: components["schemas"]["InterviewSourceKind"];
            /** Audio Filename */
            audio_filename: string;
            /** Audio Duration Sec */
            audio_duration_sec: number | null;
            type: components["schemas"]["InterviewType"];
            demographics: components["schemas"]["DemographicsSchema"];
            /** Transcript Text */
            transcript_text: string | null;
            /** Transcript Segments */
            transcript_segments: {
                [key: string]: unknown;
            }[] | null;
            /** Meeting Notes */
            meeting_notes?: string | null;
            status: components["schemas"]["InterviewStatus"];
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Processed At */
            processed_at: string | null;
            /** Pain Points */
            pain_points?: components["schemas"]["PainPointRead"][];
        };
        /**
         * InterviewSourceKind
         * @description Whether the interview source on disk is audio or a parsed transcript.
         *
         *     v1.1 adds transcript-file uploads alongside audio. The pipeline
         *     branches on this value (see ``app.services.pipeline.run_pipeline``).
         * @enum {string}
         */
        InterviewSourceKind: "audio" | "transcript";
        /**
         * InterviewStatus
         * @description Lifecycle status of an interview's processing pipeline.
         *
         *     Allowed transitions are enforced in
         *     :func:`app.services.interviews.transition_status`.
         * @enum {string}
         */
        InterviewStatus: "uploaded" | "transcribing" | "analyzing" | "completed" | "failed";
        /**
         * InterviewType
         * @description Interview taxonomy. Only one option in v0.
         * @enum {string}
         */
        InterviewType: "problem_validation";
        /**
         * JobRole
         * @description Interviewee role bucket.
         * @enum {string}
         */
        JobRole: "engineer" | "designer" | "product_manager" | "marketing" | "sales" | "operations" | "customer_support" | "founder_executive" | "student" | "other";
        /**
         * MaritalStatus
         * @description Interviewee marital status.
         * @enum {string}
         */
        MaritalStatus: "single" | "married" | "divorced" | "widowed" | "prefer_not_to_say";
        /**
         * PainPointRead
         * @description A single Claude-extracted pain point, embedded inside InterviewRead.
         */
        PainPointRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
            /** Supporting Quote */
            supporting_quote: string;
            /** Timestamp Start Sec */
            timestamp_start_sec: number;
            /** Timestamp End Sec */
            timestamp_end_sec: number;
            /** Severity */
            severity: number;
            type: components["schemas"]["PainPointType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PainPointType
         * @description Classification Claude assigns to each extracted pain point.
         *
         *     See ``SPEC_v1.1.md`` section 1 for the semantics. The default
         *     (when the customer just described the problem) is ``pain_point``;
         *     ``workaround`` and ``suggestion`` are the high-signal variants.
         * @enum {string}
         */
        PainPointType: "pain_point" | "workaround" | "suggestion";
        /**
         * ProjectCreate
         * @description Request body for ``POST /api/v1/projects``.
         */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * ProjectInsightRead
         * @description Response shape for ``GET`` / ``POST`` insights endpoints.
         *
         *     ``is_stale`` is server-computed: ``True`` when the snapshot of
         *     completed interview IDs at last generation differs from the current
         *     set. Before the first generation, ``is_stale`` is ``False`` (the
         *     UI shows the empty state in that case).
         */
        ProjectInsightRead: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            status: components["schemas"]["InsightStatus"];
            /** Summary Markdown */
            summary_markdown: string | null;
            /** Interview Count Summarised */
            interview_count_summarised: number;
            /** Interview Count Completed */
            interview_count_completed: number;
            /** Is Stale */
            is_stale: boolean;
            /** Error Message */
            error_message: string | null;
            /** Model */
            model: string | null;
            /** Generated At */
            generated_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectListResponse
         * @description List wrapper used by ``GET /api/v1/projects``.
         */
        ProjectListResponse: {
            /** Items */
            items: components["schemas"]["ProjectRead"][];
        };
        /**
         * ProjectRead
         * @description Response shape for project endpoints.
         */
        ProjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interviews_api_v1_projects__project_id__interviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interview_api_v1_projects__project_id__interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_interview_api_v1_projects__project_id__interviews_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_api_v1_interviews__interview_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_interview_api_v1_interviews__interview_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_audio_api_v1_interviews__interview_id__audio_get: {
        parameters: {
            query?: never;
            header?: {
                range?: string | null;
            };
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_insights_api_v1_projects__project_id__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInsightRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_project_insights_api_v1_projects__project_id__insights_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInsightRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
